### ISSUE TITLE
PVD Delivery 

### ISSUE THREAD

**Issue by nayana487** [ga-wdi-boston/git-basics#23]
This was the first lesson I taught and I was unsure about how much I should deviate from the set curriculum, if I could make changes to the repo so I mostly delivered as is. However, there were a couple points mentioned in the lesson that I contradicted in my delivery and some points I added. I also have some thoughts on how this lesson should be restructured. 

- The lesson plan started off with a section called `why git?` -- version control. Version control is dev speak and not something that we should expect new students to know. When I delivered, I asked them to think about working on project in a word doc--something most would be familiar with. How did you previously save changes? If someone else was working with you on the doc, how did you collaborate? What would you do if you wanted multiple versions of the project? This set them up to understand why something like git/github would be useful. Perhaps you all do something similar when you actually deliver the lesson, but for someone who was just seeing the lesson plan and doesn't have a sense of the Boston lesson flow, it was kind of confusing.

- I was kind of put off by the section that said never user `git commit -m`. That "This is surely a sign of a poor developer and one that does not respect his or her teammate's time."  This is how my instructors taught me to write commit messages and what they and pretty much every other developer I know uses in their work flow. When I delivered the lesson, I told the students that what was written in the lesson plan is the opinion of the instructor who wrote the lesson. I personally don't agree with it and this is why. It's ok and encouraged to have differing opinions as developers, but we should be able to intelligently articulate why we prefer one way over another. I did let Matt know ahead of time that I'd be saying this. That said, I don't think such strongly worded opinions should be written into a lesson plan in this way. I think --generally speaking--it's better to present different options and let students figure out what works for them. At least until the shops they end up at tell them otherwise.  

- I actually wouldn't have gotten into branching at all in a first time exposure to git lesson. Git is a pretty hard concept for complete newbies to grasp in general, and implementing branching proved very confusing to the students. If I were to deliver this again, I would talk about what branching is at a high level and why it's useful, but I wouldn't teach the implementation just yet. I think having them know about `git add`, `git status`, `git commit` and `git log` at this point is sufficient. It's what we actually need them to be doing for their homework. They can know how to look at a solution branch on an exercise in Github, but they're probably not going to be creating their own branches for a while. In DC, we do teach branching in week one, but as a separate lesson after git intro and github are introduced. Going into branching at this stage confused the students a lot and I think ultimately made it challenging the rest of the week because they were unsure about how to properly use git and github when submitting homework. 

- The Learn Git Branching tutorial was also super confusing for students. The first section `introduction to git commits` was good, but having students try to grasp detached heads and rebasing was a bit much. I personally don't mess around with rebasing too much, so I don't think students should try to either. Again, this was another thing that detracted from the fundamentals they need to understand.

**Comment by raq929** [comment]
Hi Nayana! Congrats on teaching your first lesson!!

I really like your first point, and it seems like you related it to something they would understand really well. I think we do need to introduce the term version control, because they'll run into it in interviews - but the way you did it sounds great.

re: Branching. I do think it's important to teach them about branching. It gets them to think of their projects in terms of features. More importantly, I think it's bad practice to commit directly on master, and we don't want to promote that habit. Branching allows them to have a clean, working master to come back to when they mess something else. If they commit directly on master, it's harder to go back to a clean copy. (At this level of git experience anyway.)
We do ask them to create training branches on almost every repo they clone, so they will have practice with this.

re: `git commit -m`. I agree the wording should be changed. Calling people bad developers just isn't helpful. I think the reasoning here (and @gaand might have more to say) is that at this level, developers aren't yet good at writing commit messages. Forcing them to open an editor and write a two line commit message makes them think more critically about what they're doing and produces commit messages that are more helpful to them and to us. (Personally, I only use -m when I'm making a fixup commit, for similar reasons.) 

I agree that the git branching tutorial can be a bit confusing. It does tend to work well for visual learners and not as well for others. I'm certainly open to considering different material. (I'm not in charge, though.) 😄 

In general, our practice in Boston has been to open issues on repos about things that didn't work well, and suggest changes or discussion of material, and then we fix those issues for the next iteration, depending on where the discussion goes. :) 
People do deviate some from the set curriculum, depending on the lesson plan, and their level of experience with the material. In general, if a deviation seemed really successful, we'll open an issue and add it to the material next time around.

I hope that's helpful!
~Rachel

**Comment by MicFin** [comment]
There are multiple issues in this single issue.  I am going to recommend that this be closed and the issues be opened independently as such:

Re: Version control https://github.com/ga-wdi-boston/git/issues/31
Re: Branching https://github.com/ga-wdi-boston/git/issues/29
Re: Commit -m https://github.com/ga-wdi-boston/git/issues/33
Re: Learn Git Branching https://github.com/ga-wdi-boston/git/issues/32
